language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn
- yarn run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: bot-doc-doc.surge.sh
  project: "./build/"
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_206fdc94870f_key -iv $encrypted_206fdc94870f_iv
  -in id_rsa.enc -out /tmp/.ssh/id_rsa -d
