jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:5b:e5:d6:df:6a:a3:4a:18:4e:ac:b4:a7:67:a7:2d"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: rsync -avce ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/