jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1e:2c:4f:c8:f2:08:05:19:b6:57:e2:f4:0d:f5:34:ead"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: sudo apt install -y rsync
      - run: rsync -av ssh build -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP:/root