version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1e:2c:4f:c8:f2:08:05:19:b6:57:e2:f4:0d:f5:34:ea"
      - checkout
      - restore_cache:
          keys:
            - dependencies_imooc
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_imooc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          command: ssh root@113.31.126.209