name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  push_to_registry:
    name: Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: NpmBuild
        run: npm run build

      - name: DockerBuild
        run:  docker build . -t "registry.cn-shanghai.aliyuncs.com/zzf2001/bot-doc:latest"

      - name: Login
        run:  docker login --username=${{ secrets.username }} --password=${{ secrets.password }} registry.cn-shanghai.aliyuncs.com

      - name: Push
        run:  docker push registry.cn-shanghai.aliyuncs.com/zzf2001/bot-doc

      - name: Restart
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root
            docker-compose pull
            docker-compose up -d
          host: ${{ secrets.host }}
          user: root
          pass : ${{ secrets.pass }}
          args: -tt